### ISSUE TITLE
railway power transformer disconnects from power network on save reload

### ISSUE THREAD

**Issue by Aaronstar-McClure** [DavidHGillen/Satisfactory_AB-CableChoices#10]
the railway power transformer has two (maybe three?) power connections, but does not export power

**Comment by Aaronstar-McClure** [comment]
rebuilding the transformer fixed the issue strangly. closing, but may reopen if it does not persist over saves

**Comment by Aaronstar-McClure** [comment]
power transformer disconnects from power network on save reload

**Comment by DavidHGillen** [comment]
Thanks for the report I've received one other but they couldn't verify. This seems to happen inconsistently and I don't know why. My initial testing didn't show it but I've had a couple of reports now I know it's real. I'll add some sort of mechanism for it to detect the rail rather than trusting the saved parameter. Will let you know when I've updated.

**Comment by Aaronstar-McClure** [comment]
Good to know! Would you like a copy of my save to see my setup?

**Comment by DavidHGillen** [comment]
I put in a fix for this a while back unsure if it would fix it. If it is still occurring lmk but I'm pretty sure it's solved
