### ISSUE TITLE
Power Tower Extender issue

### ISSUE THREAD

**Issue by TankerMunk** [DavidHGillen/Satisfactory_AB-CableChoices#14]
Version: CL#372858
Mod Loader v.3.8.0+483
Mod Version 1.0.6

The power tower extenders are not transmitting power to the rest of the tower. Both the standard and wide are having the issue. I have to connect the extender to the tower/additional extender that it's sitting on. I have uninstalled/reinstalled the mod, verified installed files on Steam, no resolution.

**Comment by DavidHGillen** [comment]
This is on purpose. If the different parts of the tower automatically connected to each other you wouldn't have the option of running multiple power grids like many people want. Since there's 3 connections per tower it should be easy to find a tower to connect the grids to each other if that's what you want.

I'll be reviewing this as a few people have made comments about ways they'd like it improved or changed.
